### ISSUE TITLE
VERIFY_PACKAGE_REPO mis-assigned staging instead of stage

### ISSUE THREAD

**Issue by zhangyoufu** [docker/docker-ce-packaging#942]
https://github.com/docker/docker-ce-packaging/blob/dfe2ab9d0af9c8e875d56510c1a436edd51913d4/common.mk#L44-L46

@thaJeztah introduced in #697

related code:
https://github.com/docker/docker-ce-packaging/blob/dfe2ab9d0af9c8e875d56510c1a436edd51913d4/Makefile#L94-L98
https://github.com/docker/docker-ce-packaging/blob/dfe2ab9d0af9c8e875d56510c1a436edd51913d4/install-containerd-helpers#L13
https://github.com/docker/docker-ce-packaging/blob/dfe2ab9d0af9c8e875d56510c1a436edd51913d4/install-containerd-helpers#L42

**Comment by thaJeztah** [comment]
Oh, great catch! I think I must've committed from the wrong state; I recall now that when I was upstreaming these patches from our internal repository (see https://github.com/docker/docker-ce-packaging/pull/697) that I was considering changing this to `staging` instead of `stage`, because the repo-file is named `docker-ce-staging.repo`, but then realised the _domain_ uses `stage`, so that wouldn't work (so I didn't make those changes 😅) https://github.com/docker/docker-ce-packaging/blob/dfe2ab9d0af9c8e875d56510c1a436edd51913d4/install-containerd-helpers#L14-L14


The default here should be either "empty", or "something else" (the `download-stage.docker.com` domain cannot be used as a default, because packages are frequently pushed there "temporarily" after which they are removed again, or replaced with newer builds for the same version before they go to production).


I think it's safer to set it to a non-empty value, and to use "something else"; looking at our internal pipeline, we set this value to `prod` as default (which is "something else").q

Are you interested in contributing and to open a pull request? (if you do, don't forget to include a DCO signed-off-by line in your commit message; see https://github.com/docker/cli/blob/v24.0.6/CONTRIBUTING.md#sign-your-work)

If not, I'm happy to open a quick pull request as well :smile:
