### ISSUE TITLE
[BUG] docker compose in apt is not up to date with docker compose releases

### ISSUE THREAD

**Issue by mageebr** [docker/docker-ce-packaging#967]
**NOTE:** This issue is copied from the Docker Compose Site that was closed:
[issue-11202] (https://github.com/docker/compose/issues/11202#issue-1999489741)

### Description
docker_compose: **2.23.1** is not available in the apt repository.

docker compose release history:
https://docs.docker.com/compose/release-notes/

**2.23.1** does not match the latest in apt with is currently **v2.21.0**.

### Steps To Reproduce

1. Check the Docker-Compose Release notes for the lastest version.
[docker-compose release notes](https://github.com/docker/compose/releases)

1. Check the version available from the Ubuntu repo.

$ **apt-cache madison docker-compose-plugin**
docker-compose-plugin | 2.21.0-1 ubuntu.22.04-jammy | https://download.docker.com/linux/ubuntu jammy/stable amd64 Packages
docker-compose-plugin | 2.20.2-1 ubuntu.22.04-jammy | https://download.docker.com/linux/ubuntu jammy/stable amd64 Packages
docker-compose-plugin | 2.19.1-1 ubuntu.22.04-jammy | https://download.docker.com/linux/ubuntu jammy/stable amd64 Package

**Comment from Previous Issue**

- It looks like someone on the packaging team needs to work with the docker-compose team to coordinate releases.

**Comment by thaJeztah** [comment]
docker compose is incompatible with go1.20 (see https://github.com/docker/docker-ce-packaging/pull/965), which is the version used to build packages of docker engine 24.x, unfortunately that means that no new packages can be published until either docker v25 is released, or docker v24 switches to go1.21 or above (there's a lot of risk involved in updating go version of the docker engine, which is why it tends to be a version behind).

docker 25 will be released soon though; beta packages are already available in the test channel, which also has package of docker compose v2.23.3 (see https://download.docker.com/linux/ubuntu/dists/jammy/pool/test/amd64/)

Alternatively, static binaries can be downloaded from the github repository https://github.com/docker/compose/releases

I'll close this ticket, as this will be resolved once docker engine v25 is released, but feel free to continue the conversation.

**Comment by RossBarnie** [comment]
Is this still relevant for docker compose 2.24.2? I realise it's only been a day but I was surprised to see that the patch was released but the package in the PPA was still 2.24.1.

**Comment by thaJeztah** [comment]
The version has been updated in https://github.com/docker/docker-ce-packaging/pull/981, and updated package versions will be built and published when we do the next (v25.0.1) release of  Docker Engine, which should be this week (Today or Tomorrow)
